

export const signUp = async(req , res , next)=>{
   
    try {
        
    } catch (error) {
        
    }

}